background {
    monitor =
    path = screenshot
    blur_passes = 4
    blur_size = 8
    noise = 0.0
    contrast = 0.95
    brightness = 0.85
    vibrancy = 0.12
}


input-field {
    monitor =
    size = 260, 52
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.35)
    outer_color = rgba(255, 255, 255, 0.35)
    font_color = rgba(255, 255, 255, 0.95)
    placeholder_text = Password...
    hide_input = false
    fade_on_empty = false
    position = 0, -35
    halign = center
    valign = center
}
